const names = {
    human: {
        familyNames: [
            'Kennedy',
            'Gardener',
            'Williams',
            'Tillerman', 
            'Johnson',
            'Roberts',
            'Wright',
            'Green',
            'Jackson',
            'Hill',
            'Baker',
            'Young',
            'Richardson',
            'Wilkinson',
            'Hunt',
            'West',
            'Knight',
            'Fisher',
            'Saunders',
            'Booth',
            'Armstrong',
            'Stephens',
            'Frost',
            'McDonald',
            'Lawrence',
        ],
        firstNames: [
            'James',
            'Robert',
            'Johnny',
            'Michael',
            'David',
            'William',
            'Richard',
            'Joseph',
            'Daniel',
            'Charles',
            'Matthew',
            'Anthony',
            'Mark',
            'Donald',
            'Steven',
            'Paul',
            'Andrew',
            'Joshua',
            'Kenneth',
            'Kevin',
            'Brian',
            'George',
            'Timothy',
            'Ronald',
            'Jason',
            'Jeffrey',
            'Ryan',
            'Jacob',
            'Gary',
            'Eric',
            'Larry',
            'Justin',
            'Scott',
            'Brandon',
            'Benjamin',
            'Samuel',
            'Gregory',
            'Frank',
            'Patrick',
            'Raymond',
            'Jack',
            'Dennis',
            'Jerry',
            'Tyler',
            'Aaron',
            'Adam',
            'Nathan',
            'Henry',
            'Douglas',
            'Zachary',
            'Peter',
            'Kyle',
            'Jeremy',
            'Christian',
            'Keith',
            'Roger',
            'Terry',
            'Sean',
            'Austin',
            'Carl',
            'Dylan',
            'Jesse',
            'Jordan',
            'Billy',
            'Alan',
            'Wayne',
            'Randy',
            'Bobby',
            'Mason',
            'Philip',
            'Owen',
            'Aiden',
            'Leo',
            'Carter',
            'Lincoln',
            'Maverick',
            'Caleb',
            'Xavier',
            'Cameron',
            'Ryan',
            'Colton',
            'Ian',
            'Beau',
            'Parker',
            'Declan',
            'Kayden',
            'River',
            'Chase',
            'Walker',
            'Braxton',
            'Ace',
            'Graham',
            'Tucker',
            'Samson',
            'Brody',
            'Ariel',
            'Dawson',
            'Nash',
            'Simon',
            'Micky',
        ]
    },
    nocturne: {
        familyNames: [
            'Bloodwood',
            'Nightshade',
            'St.Clair',
            'Belladonna',
            'Ramsay',
            'Vaculai',
            'Orwell',
            'Salem',
            'VanHorne',
            'Dracia',
            'Noir',
        ],
        firstNames: [
            'Dante',
            'Victor',
            'Edward',
            'Alaric',
            'Blaise',
            'Ephraim',
            'Jasper',
            'Klaus',
            'Sylvester',
            'Thorne',
            'Willow',
            'Dominic',
            'Oliver',
            'Armand',
            'Nicholas',
            'Solomon',
            'Tobias',
            'Edgar',
            'Vincent',
            'Drac',
            'Gustav',
            'Alistair',
            'Hannibal',
            'Dorian',
            'Gray',
            'Drystan',
            'Erik',
            'Rufus',
            'Silas',
            'Leif',
            'Oscar',
            'Vlad',
            'Cain',
            'Lucian',
            'Raven',
            'Finn',
            'Valentine',
            'Casper',
            'Everett',
            'Benedict',
            'Branislav',
            'Blake',
            'Augustus',
            'Christopher',
            'Desmond',
            'Eli',
            'Thomas',
            'Poe',
            'Maxwell',
            'Damian',
            'Amon',
            'Leviathan',
            'Samael',
            'Seth',
            'Ambrosia',
            'Bartholomew',
            'Lazarus',
            'Magnus',
            'Orpheus',
            'Talon',
            'Xander',
            'Salvatore',
            'Mortimer',
            'Gabriel',
            'Petrie',
            'Morpheus',
            'Marlowe',
            'Atticus', 
            'Serpentine',
            'Maine',
            'Carnegie',
            'Ipswich',
            'Rasputin',
            'Lyle',
            'Westminster',
            'Niles',
            'Shawshank',
            'Beethoven',
            'Lester',
            'Massachusetts',
            'Reid',
            'Theodore',
            'Ivan',
            'Octavius',
            'Linus',
            'Rainier',
            'Abraham',
            'Ezekiel',
            'Jeremiah',
            'Nathaniel',
            'Zachariah',
            'Ignacio',
            'Pascal',
            'Elmer',
            'Frederik',
            'Byron',
            'Donovan',
            'Fergus',
            'Huxley',
            'Newton',
            'Stein',
            'Preston',
            'Royce',
            'Vernon',
            'Winston',
            'Marlborough',
            'Juniper',
            'Art',
            'Killbert',
            'Moreton',
            'Earle',
            'Deville',
            'Milton',
            'Cadaver',
            'Osbourne',            
        ]
    },
    'hive': {
        familyNames: [
            'X',
            'AAA',
            'cDZ8',
            'F300',
            'bY4V199',
            'P11R',
            'L1',
            'P0Lyd',
            'znK',
            'lYNx',
            'r1c3r',
        ],
        firstNames: [
            '001', '002', '003', '004', '005', '006',
            '007', '008', '009', '010', '011', '012', '013',
            '014', '015', '016', '017', '018', '019', '020',
            '021', '022', '023', '024', '025', '026', '027',
            '028', '029', '030', '031', '032', '033', '034',
            '035', '036', '037', '038', '039', '040', '041',
            '042', '043', '044', '045', '046', '047', '048',
            '049', '050', '051', '052', '053', '054', '055',
            '056', '057', '058', '059', '060', '061', '062',
            '063', '064', '065', '066', '067', '068', '069',
            '070', '071', '072', '073', '074', '075', '076',
            '077', '078', '079', '080', '081', '082', '083',
            '084', '085', '086', '087', '088', '089',
        ]
    },
    'acacia': {
        familyNames: [
            'Moksha',
            'Sils',
            'Brahman',
            'Calpa',
            'Nea',
            'Deva',
            'Mannu',
            'Ashura',
            'Shivah',
            'Tundava',
            'Sunsara',
        ],
        // 63 First names
        firstNames: [
            'First', 'First', 'First', 'First',
            'First', 'First', 'First', 'First',
            'First', 'First', 'First', 'First',
            'First', 'First', 'First', 'First',
            'First', 'First', 'First', 'First',
            'First', 'First', 'First', 'First',
            'First', 'First', 'First', 'First',
            'First', 'First', 'First', 'First',
            'First', 'First', 'First', 'First',
            'First', 'First', 'First', 'First',
            'First', 'First', 'First', 'First',
            'First', 'First', 'First', 'First',
            'First', 'First', 'First', 'First',
            'First', 'First', 'First', 'First',
            'First', 'First', 'First', 'First',
            'First', 'First', 'First'
        ]
    },
    'the chosen': {
        familyNames: [
            'Xil',
            'Sadik',
            'Kepri',
            'Amsi',
            'Amen',
            'Babafemi',
            'Hapi',
            'Harakhty',
            'Hu',
            'Kek',
            'Mesi',
        ],
        firstNames: [
            'Ra',
            'Ur',
            'Asim',
            'Chisisi',
            'Gyasi',
            'Khons',
            'Sadiiki',
            'Aharon',
            'Akhenaten',
            'Apep',
            'Baahir',
            'Horus',
            'Imhotep',
            'Abraxas',
            'Zahur',
            'Moke',
            'Ter',
            'Zu',
            'Ren',
            'Atah',
            'Nyhz',
            'Let',
            'Zarx',
            'Crexa',
            'Abubakar',
        ]
    },
}

function generateNames() {
    let fullNames = {}

    Object.keys(names).forEach(factionName => {
        fullNames[factionName] = []
    })

    const reduced = Object.entries(names).reduce((acc, [faction, familyObj]) => {
        const { familyNames, firstNames } = familyObj

        familyNames.forEach(familyName => {
            firstNames.forEach(firstName => {
                acc[faction].push(`${firstName} ${familyName}`)
            })
        })
    
        return acc
    }, Object.keys(names).reduce((acc, k) => {
        acc[k] = []
        return acc
    }, {}))

    // const factionLengths = Object.entries(reduced).map(([faction, familyObj]) => {
    //     return {
    //         [faction]: familyObj.length
    //     }
    // })

    // const totalLength = Object.entries(reduced).reduce((acc, [faction, familyObj]) => {
    //     acc = acc + familyObj.length
    //     return acc
    // }, 0)
    
    // console.log(factionLengths)
    // console.log(totalLength)

    return Object.entries(reduced).reduce((acc, [faction, names]) => {
        acc[faction] = names.sort(() => Math.random() - 0.5)
        return acc;
    }, {})
}

const counts = Object.entries(names).reduce((acc, [faction, familyObj]) => {
    familyObj.familyNames.forEach(family => {
        acc[faction].expectedCount = acc[faction].expectedCount + family.count
    })
    
    return acc
}, Object.keys(names).reduce((acc, k) => {
    acc[k] = { expectedCount: 0 }
    return acc
}, {}))

const generatedNames = generateNames()

module.exports = {
    generatedNames
}